TRAINING: True
DATASET_ROOT: "/home/david/dd2424_image_generation/datasets/flickr30k"
WORKERS: 2 
N_GPU: 1

BATCH_SIZE: 32

IMAGE_WIDTH: 64
IMAGE_HEIGHT: 64
N_COLOR_CHANNELS: 3

N_LATENT_VECTOR: 64
N_GENERATOR_FEATURE_MAP: 64
N_DISCRIMINATOR_FEATURE_MAP: 64

N_TRAINING_EPOCHS: 200
LEARNING_RATE: 0.0002

BETA1: 0.5
VERBOSE: 3
SEED: 888
