TRAINING: True
DATASET_ROOT: "datasets/flickr30k_resized_tiny"
WORKERS: 1
N_GPU: 1

BATCH_SIZE: 128

IMAGE_WIDTH: 500
IMAGE_HEIGHT: 375
N_COLOR_CHANNELS: 3

N_LATENT_VECTOR: 100
N_GENERATOR_FEATURE_MAP: 64
N_DISCRIMINATOR_FEATURE_MAP: 64

N_TRAINING_EPOCHS: 8
LEARNING_RATE: 0.0002

BETA1: 0.5
